"""add customer profiles and appointment concerns

Revision ID: 40f931fff647
Revises: 054cec3fb0de
Create Date: 2026-09-24 14:30:11.199318
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '40f931fff647'
down_revision: Union[str, None] = '054cec3fb0de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if not inspector.has_table('customer_profiles'):
        op.create_table('customer_profiles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('gender', sa.String(length=40), nullable=True),
        sa.Column('age', sa.Integer(), nullable=True),
        sa.Column('weight_kg', sa.Float(), nullable=True),
        sa.Column('medical_notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
        )
    if 'concern' not in {column['name'] for column in inspector.get_columns('appointments')}:
        op.add_column('appointments', sa.Column('concern', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'concern')
    op.drop_table('customer_profiles')
    # ### end Alembic commands ###
