// @ts-nocheck
import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import './App.css'

type User = { id: number; name: string; email: string; role: string }
type Provider = { id: number; name: string; specialization?: string }
type Appointment = { id: number; provider_id: number; start_datetime: string; end_datetime: string; status: string; concern?: string }
type Slot = { start_datetime: string; end_datetime: string }
type Profile = { id: number; user_id: number; name: string; email: string; gender?: string; age?: number; weight_kg?: number; medical_notes?: string }
type Confirmation = { text: string; action: () => Promise<void> }

async function api<T>(url: string, options: RequestInit = {}): Promise<T> {
  const token = sessionStorage.getItem('appointment_token')
  const response = await fetch(url, { ...options, headers: { ...(options.body ? { 'Content-Type': 'application/json' } : {}), ...(token ? { Authorization: `Bearer ${token}` } : {}) } })
  if (response.status === 401) {
    sessionStorage.clear()
    window.location.reload()
    throw new Error('Session expired. Please sign in again.')
  }
  if (!response.ok) throw new Error((await response.json().catch(() => null))?.detail ?? 'Request failed')
  return response.status === 204 ? (undefined as T) : response.json()
}

const timeLabel = (value: string) => new Intl.DateTimeFormat('en', { hour: 'numeric', minute: '2-digit' }).format(new Date(value))

function ConfirmModal({ item, close, confirm }: { item: Confirmation; close: () => void; confirm: () => void }) {
  return <div className="modal-backdrop"><section className="confirm-modal" role="dialog" aria-modal="true"><p className="eyebrow">Please confirm</p><h2>{item.text}</h2><p className="modal-copy">This action will update your appointment record.</p><div className="modal-actions"><button className="secondary" onClick={close}>Keep it</button><button className="primary modal-confirm" onClick={confirm}>Confirm</button></div></section></div>
}

function App() {
  const [user, setUser] = useState<User | null>(() => { const saved = sessionStorage.getItem('appointment_user'); return saved ? JSON.parse(saved) : null })
  const [message, setMessage] = useState('')
  const [providers, setProviders] = useState<Provider[]>([])
  const [appointments, setAppointments] = useState<Appointment[]>([])
  const [profile, setProfile] = useState<Profile | null>({ id: 0, user_id: 0, name: '', email: '', gender: '', age: undefined, weight_kg: undefined, medical_notes: '' })
  const [view, setView] = useState(() => window.location.hash.slice(1) || 'overview')
  const [confirmation, setConfirmation] = useState<Confirmation | null>(null)

  useEffect(() => { window.addEventListener('hashchange', () => setView(window.location.hash.slice(1) || 'overview')); return () => window.removeEventListener('hashchange', () => undefined) }, [])
  useEffect(() => { api<Provider[]>('/providers').then(setProviders).catch(() => setMessage('Start the backend on port 8000.')) }, [])
  useEffect(() => { if (user) api<Appointment[]>('/appointments').then(setAppointments).catch(() => undefined) }, [user])
  useEffect(() => { if (user?.role === 'CUSTOMER') api<Profile>('/users/me/profile').then(setProfile).catch(() => undefined) }, [user])

  async function login(event: FormEvent) { event.preventDefault(); try { const result = await api<{ access_token: string; user: User }>('/auth/login', { method: 'POST', body: JSON.stringify({ email: (event.currentTarget as HTMLFormElement).email.value, password: (event.currentTarget as HTMLFormElement).password.value }) }); sessionStorage.setItem('appointment_token', result.access_token); sessionStorage.setItem('appointment_user', JSON.stringify(result.user)); setUser(result.user) } catch (error) { setMessage(error instanceof Error ? error.message : 'Login failed') } }
  function logout() { sessionStorage.clear(); setUser(null) }
  function cancel(appointment: Appointment) { setConfirmation({ text: 'Cancel this appointment?', action: async () => { await api(`/appointments/${appointment.id}/cancel`, { method: 'POST' }); setAppointments(await api<Appointment[]>('/appointments')); setMessage('Appointment cancelled.') } }) }

  if (!user) return <main className="auth-shell"><div className="auth-panel"><div className="brand-mark">A<span>/</span>S</div><p className="eyebrow">Appointment Scheduling</p><h1>Make time for what matters.</h1><p className="lede">Find a provider, choose a time, and keep your day moving.</p><form onSubmit={login} className="auth-form"><h2>Welcome back</h2><label>Email<input name="email" type="email" required /></label><label>Password<input name="password" type="password" required /></label><button className="primary">Sign in</button></form>{message && <p className="notice">{message}</p>}</div><div className="auth-art"><div className="art-note">01 <span>Find your rhythm</span></div><div className="art-sun" /><div className="art-copy">Thoughtful scheduling<br /><em>for real life.</em></div></div></main>
  if (user.role !== 'CUSTOMER') return <RoleView user={user} appointments={appointments} providers={providers} logout={logout} cancel={cancel} />
  return <CustomerView user={user} providers={providers} appointments={appointments} profile={profile} setProfile={setProfile} setAppointments={setAppointments} message={message} setMessage={setMessage} view={view} setConfirmation={setConfirmation} confirmation={confirmation} logout={logout} />
}

function CustomerView({ user, providers, appointments, profile, setProfile, setAppointments, message, setMessage, view, setConfirmation, confirmation, logout }: any) {
  const navigate = (page: string) => { window.location.hash = page; setTimeout(() => document.getElementById(page)?.scrollIntoView({ behavior: 'smooth' }), 0) }
  return <div className="app-shell"><aside className="sidebar"><div className="brand-mark">A<span>/</span>S</div><div className="side-title">Your day,<br /><strong>in balance.</strong></div><nav><a className={view === 'overview' ? 'active' : ''} onClick={() => navigate('overview')}>Overview</a><a className={view === 'appointments' ? 'active' : ''} onClick={() => navigate('appointments')}>Appointments</a><a className={view === 'profile' ? 'active' : ''} onClick={() => navigate('profile')}>Profile</a></nav><div className="side-foot"><div className="avatar">{user.name[0]}</div><div><strong>{user.name}</strong><small>customer</small></div><button onClick={logout}>↗</button></div></aside><main className="dashboard"><header><div><p className="eyebrow">Customer workspace</p><h1>{view === 'appointments' ? 'Your appointments.' : view === 'profile' ? 'Your profile.' : `Good morning, ${user.name.split(' ')[0]}.`}</h1></div><div className="status"><i /> System operational</div></header>{message && <div className="notice inline">{message}</div>}{view === 'overview' && <Overview appointments={appointments} providers={providers} />}{view === 'profile' && <ProfilePage profile={profile} setProfile={setProfile} setMessage={setMessage} />}{view === 'appointments' && <AppointmentsPage providers={providers} appointments={appointments} setAppointments={setAppointments} setMessage={setMessage} setConfirmation={setConfirmation} />}{confirmation && <ConfirmModal item={confirmation} close={() => setConfirmation(null)} confirm={async () => { await confirmation.action(); setConfirmation(null) }} />}</main></div>
}

function Overview({ appointments, providers }: { appointments: Appointment[]; providers: Provider[] }) { const next = appointments.find((appointment) => appointment.status === 'CONFIRMED'); const doctor = next ? providers.find((provider) => provider.id === next.provider_id)?.name : null; return <section className="overview-panel page-panel"><p className="eyebrow overview-kicker">Basic overview</p><h2>Your day at a glance</h2><div className="metric-row"><div><span>Coming appointments</span><strong>{appointments.filter((a) => a.status === 'CONFIRMED').length}</strong></div><div><span>Doctors available</span><strong>{providers.length}</strong></div><div><span>Next appointment</span><strong>{next ? <><em>{doctor || 'Doctor'}</em>{timeLabel(next.start_datetime)}</> : '—'}</strong></div></div></section> }

function ProfilePage({ profile, setProfile, setMessage }: any) { async function save(event: FormEvent) { event.preventDefault(); setProfile(await api<Profile>('/users/me/profile', { method: 'PUT', body: JSON.stringify(profile) })); setMessage('Profile saved.') } return <section className="profile-panel page-panel"><p className="eyebrow">Personal information</p><h2>Basic health details</h2>{profile && <form className="profile-form" onSubmit={save}><div className="profile-fields"><input placeholder="Gender" value={profile.gender || ''} onChange={(e) => setProfile({ ...profile, gender: e.target.value })} /><input placeholder="Age" type="number" value={profile.age || ''} onChange={(e) => setProfile({ ...profile, age: Number(e.target.value) })} /><input placeholder="Weight (kg)" type="number" value={profile.weight_kg || ''} onChange={(e) => setProfile({ ...profile, weight_kg: Number(e.target.value) })} /></div><textarea placeholder="Basic medical notes" value={profile.medical_notes || ''} onChange={(e) => setProfile({ ...profile, medical_notes: e.target.value })} /><button className="secondary" type="submit">Save profile</button></form>}</section> }

function AppointmentsPage({ providers, appointments, setAppointments, setMessage, setConfirmation }: any) { const [doctor, setDoctor] = useState<Provider | null>(null); const [date, setDate] = useState('2026-09-28'); const [concern, setConcern] = useState(''); const [slots, setSlots] = useState<Slot[]>([]); async function selectDoctor(provider: Provider) { setDoctor(provider); setSlots((await api<{ slots: Slot[] }>(`/providers/${provider.id}/availability?target_date=${date}`)).slots) } function book(slot: Slot) { if (!concern.trim() || !doctor) { setMessage('Enter a concern before booking.'); return } setConfirmation({ text: `Book ${timeLabel(slot.start_datetime)} with ${doctor.name}?`, action: async () => { await api('/appointments', { method: 'POST', body: JSON.stringify({ provider_id: doctor.id, start_datetime: slot.start_datetime, end_datetime: slot.end_datetime, concern }) }); setAppointments(await api<Appointment[]>('/appointments')); setMessage('Appointment confirmed.') } }) } return <section className="appointments-page page-panel"><div className="section-heading"><div><p className="eyebrow">Doctors and times</p><h2>Create or manage appointments</h2></div><input className="date-input" type="date" value={date} onChange={async (e) => { setDate(e.target.value); if (doctor) setSlots((await api<{ slots: Slot[] }>(`/providers/${doctor.id}/availability?target_date=${e.target.value}`)).slots) }} /></div><label className="concern-field">Concern for the doctor<textarea value={concern} onChange={(e) => setConcern(e.target.value)} placeholder="Briefly describe your concern" /></label><div className="provider-grid">{providers.map((provider: Provider) => <button className="provider-card" key={provider.id} onClick={() => selectDoctor(provider)}><span className="provider-icon">{provider.name[0]}</span><span><strong>{provider.name}</strong><small>{provider.specialization || 'Doctor'}</small></span><b>→</b></button>)}</div>{doctor && <div className="slots"><p>Available with {doctor.name}</p><div className="slot-grid">{slots.map((slot) => <button key={slot.start_datetime} onClick={() => book(slot)}>{timeLabel(slot.start_datetime)}<small>30 min</small></button>)}</div></div>}<h2 className="section-title">Your appointments</h2><div className="appointment-list">{appointments.map((appointment: Appointment) => <article key={appointment.id}><div className="appointment-info"><strong>{providers.find((p: Provider) => p.id === appointment.provider_id)?.name || 'Doctor'}</strong><span>{timeLabel(appointment.start_datetime)} · {appointment.status.toLowerCase()}</span><small>{appointment.concern || 'No concern provided'}</small></div></article>)}</div></section> }

function RoleView({ user, appointments, providers, logout, cancel }: any) { return <div className="app-shell"><aside className="sidebar"><div className="brand-mark">A<span>/</span>S</div><div className="side-title">{user.role === 'ADMIN' ? 'System view,' : 'Your practice,'}<br /><strong>in focus.</strong></div><nav><a className="active">Overview</a><a>Appointments</a></nav><div className="side-foot"><div className="avatar">{user.name[0]}</div><div><strong>{user.name}</strong><small>{user.role.toLowerCase()}</small></div><button onClick={logout}>↗</button></div></aside><main className="dashboard"><header><div><p className="eyebrow">{user.role === 'ADMIN' ? 'Operations console' : 'Provider workspace'}</p><h1>{user.role === 'ADMIN' ? 'System at a glance.' : `Good morning, ${user.name}.`}</h1></div></header><section className="appointments-panel page-panel"><h2>Appointments</h2><div className="appointment-list">{appointments.map((appointment: Appointment) => <article key={appointment.id}><div className="appointment-info"><strong>Appointment #{appointment.id}</strong><span>{timeLabel(appointment.start_datetime)} · {appointment.status.toLowerCase()}</span><small>{appointment.concern || 'No concern provided'}</small></div>{appointment.status === 'CONFIRMED' && <button onClick={() => cancel(appointment)}>×</button>}</article>)}</div></section></main></div> }

export default App
